### ISSUE TITLE
GeckoDriver "Not in GZip Format"

### ISSUE THREAD

**Issue by jeffnyman** [titusfortner/webdrivers#6] opened 2017-11-08 12:21 UTC
I get this error every time when it's attempting to use the file geckodriver-v0.19.1-macos.tar.gz:

    `initialize': not in gzip format (Zlib::GzipFile::Error)

I have confirmed that the above file is downloaded and placed in the ./webdrivers directory. This is just using the gem "out of the box", no special setup or weird configurations.

The error is happening on this line:

https://github.com/titusfortner/webdrivers/blob/master/lib/webdrivers/common.rb#L141

Update:

I've confirmed that what gets downloaded is 0 bytes. So this may be related to this issue: https://github.com/titusfortner/webdrivers/issues/3. However, when I change my local copy to use that code, the issue still appears because it's occurring on that first line, so it never gets to the subsequent lines that are presumably providing the fix.

This file (geckodriver-v0.19.1-macos.tar.gz) is apparently being downloaded as a zero byte file in the first place.

**Comment by titusfortner** [comment] 2017-11-20 19:32
I can't reproduce this issue. If you ever had webdrivers 2.x installed, make sure you `bundle uninstall webdrivers` and make sure there is no 2.x. Then delete your `~/.webdrivers` directory and it should work. It should override a bad copy of geckodriver assuming the remote server is working and you are connected to the internet.

**Comment by titusfortner** [comment] 2018-01-04 19:35
@jeffnyman if this is still an issue with the latest version, I'll re-open, until then, I'm closing as can't-reproduce. Thanks for raising the issue.

**Closed as completed by titusfortner** 2018-01-04 19:35 UTC
