### ISSUE TITLE
Undefined Method '[]' for nil:NilClass

### ISSUE THREAD

**Issue by viecode09** [titusfortner/webdrivers#19] opened 2018-09-18 00:39 UTC
I got this following error below when trying to use chromedriver in parallel, could you please help me what happened and how to fix it?
All supported really appreciated much.

```
#<NoMethodError: undefined method `[]' for nil:NilClass>
  /Users/lutvirosyady/.rvm/gems/ruby-2.5.0/gems/webdrivers-3.4.0/lib/webdrivers/chromedriver.rb:12:in `current'
  /Users/lutvirosyady/.rvm/gems/ruby-2.5.0/gems/webdrivers-3.4.0/lib/webdrivers/common.rb:190:in `correct_binary?'
  /Users/lutvirosyady/.rvm/gems/ruby-2.5.0/gems/webdrivers-3.4.0/lib/webdrivers/common.rb:22:in `update'
  /Users/lutvirosyady/.rvm/gems/ruby-2.5.0/gems/webdrivers-3.4.0/lib/webdrivers/selenium.rb:7:in `driver_path'
  /Users/lutvirosyady/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/chrome/driver.rb:38:in `initialize'
  /Users/lutvirosyady/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
  /Users/lutvirosyady/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
  /Users/lutvirosyady/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver.rb:86:in `for'
```

**Comment by nicolascian** [comment] 2018-09-18 13:59
Same on release (3.4.1)

```
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/webdrivers-3.4.1/lib/webdrivers/chromedriver.rb:12:in `current': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/nicolas/.rvm/gems/ruby-2.3.1/gems/webdrivers-3.4.1/lib/webdrivers/common.rb:190:in `correct_binary?'
	from /home/nicolas/.rvm/gems/ruby-2.3.1/gems/webdrivers-3.4.1/lib/webdrivers/common.rb:22:in `update'
	from /home/nicolas/.rvm/gems/ruby-2.3.1/gems/webdrivers-3.4.1/lib/webdrivers/selenium.rb:7:in `driver_path'
	from /home/nicolas/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/chrome/driver.rb:37:in `initialize'
	from /home/nicolas/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
	from /home/nicolas/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
	from /home/nicolas/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver.rb:86:in `for'
	from /home/nicolas/.rvm/gems/ruby-2.3.1/gems/watir-6.12.0/lib/watir/browser.rb:48:in `initialize'
```

**Comment by mascolim** [comment] 2018-09-18 14:00
(At webdrivers\chromedriver.rb 12)
I believe the issue is in the regex for the current chromedriver version which is:
`        normalize string.match(/ChromeDriver (\d\.\d+)/)[1]` 
Which is not matching double digit versions. So the potential solution could be to change it to:
`        normalize string.match(/ChromeDriver (\d+\.\d+)/)[1]`
Edit: This only ignores the real problem which is the weird Chromedriver 70 verion as @nicolascian pointed out below. Which should be 2.42

**Comment by viecode09** [comment] 2018-09-18 14:34
@mascolim This seems to be working with your solution. I'll test it on my side before I create PR if necessary.

Thanks for your help.

**Comment by nicolascian** [comment] 2018-09-18 14:36
Using <= 3.4.0 has downloaded the weird ChromeDriver 70 version, and you want the 2.42 version

```
require 'webdrivers'
Webdrivers.logger.level = :debug
Webdrivers::Chromedriver.current
2018-09-18 11:31:48 DEBUG Webdrivers Checking current version
2018-09-18 11:31:48 DEBUG Webdrivers File is already downloaded: true
2018-09-18 11:31:48 DEBUG Webdrivers Current version of /home/nicolas/.webdrivers/chromedriver is ChromeDriver 70.0.3538.16
```

Delete this version from folder .webdrivers and upgrade to 3.4.1

**Comment by mascolim** [comment] 2018-09-18 15:21
Once the LATEST_RELEASE fix is merged it may still be beneficial to include the regex change or error handling when fetching the current version to prevent exceptions for those who happened to pick up the experimental chromedriver version.

**Closed as completed** 2018-10-16 01:22 UTC
