### ISSUE TITLE
Webdrivers::VersionError: Unable to find latest point release version for 85.0.4182

### ISSUE THREAD

**Issue by breathe** [titusfortner/webdrivers#180] opened 2020-08-13 01:55 UTC
#### Summary
Getting this error in CI when I try to update chromium:

```
       Webdrivers::VersionError: Unable to find latest point release version for 85.0.4182. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
```

The chromium version installed in my environment is determined by the puppeteer npm module (our app image has some codepaths that automate chromium via selenium from ruby and other codepaths that automate chromium by puppeteer -- puppeteer is tightly coupled to chromium version so we let it decide the version of chromium -- and then use webdrivers to install the compatible selenium drivers needed to support the ruby codepaths ...)

 
#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version:

```
    webdrivers (4.4.1)
```

* Ruby version:

```
~ $ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

* Operating system / CI Environment:

```
heroku stack-18
```

* Browser and version:
```
{"chromiumPath":"./node_modules/puppeteer/.local-chromium/linux-782078/chrome-linux/chrome"}
```

#### Expected Behavior
Chromedriver with correct version would be installed

#### Actual Behavior
Failure about that the needed version doesn't exist

**Comment by titusfortner** [comment] 2020-08-13 02:19
Technically there is no "correct" version of chromedriver for a non production version of chrome. Webdrivers follows the recommendations specified by Google:  https://chromedriver.chromium.org/downloads/version-selection

My default is to stick with Google recommendations and for users to specify what they want if they are doing something special. You should be able to programmatically get the version of chromium installed by the npm and determine what version of chromedriver is close enough for you.

**Comment by kapoorlakshya** [comment] 2020-09-29 06:52
Hi @breathe, do you have what you need from us to resolve this issue? If yes, then I would like to close this issue. Thank you!

**Comment by kapoorlakshya** [comment] 2020-10-04 02:36
Closing due to lack of response.

@breathe Please feel free to open a new issue or comment here if you need further assistance.

**Closed as completed by kapoorlakshya** 2020-10-04 02:36 UTC

**Comment by marckohlbrugge** [comment] 2020-12-20 12:05
I'm running into a similar issue after [removing Chrome](https://chromeisbad.com), and installing Chromium instead. I'd expect it to work out of the box as it did when using Chrome.

I tried explicitly setting the `required_version` to `"89.0.4354.0"`but that leads to a 404 when trying to download the file.

Would it be possible to include step-by-step instructions in the Readme for getting webdrivers to work with Chromium?

**Comment by kapoorlakshya** [comment] 2020-12-20 17:39
@marckohlbrugge Would you mind creating a new issue? The 404 sounds like a new problem, and will need environment info, especially the OS, to reproduce the Chromium issue. Thanks!

**Comment by kapoorlakshya** [comment] 2020-12-20 17:41
And feel free to link this issue in the new one for context.

**Comment by kapoorlakshya** [comment] 2020-12-21 03:15
I am looking into the 404 error and turns out v89 is not listed on the downloads index - https://chromedriver.storage.googleapis.com/index.html

You'll have to specify a required version indexed on that page.

**Comment by marckohlbrugge** [comment] 2020-12-21 11:05
> I am looking into the 404 error and turns out v89 is not listed on the downloads index - https://chromedriver.storage.googleapis.com/index.html
> 
> You'll have to specify a required version indexed on that page.

I see. I'm beginning to understand how webdrivers, chromedriver, chrome, and chromium all play together. I've created issue #188 to address this. It would be nice if using webdrivers with Chromium was as easy as it is with Chrome.
